// 流程圖選單設定檔
// 修改此檔案即可新增、刪除或更名功能按鈕
// icon 請參考 https://lucide.dev 挑選圖標名稱

export const flowSections = [
  {
    id: "customer",
    label: "客戶端",
    color: "orange",
    items: [
      {
        id: "customers",
        label: "客戶資料",
        icon: "Users",
        href: "/customers",
        description: "客戶基本資料管理",
        active: true,
      },
      {
        id: "quotation",
        label: "報價單",
        icon: "FileText",
        href: "/quotation",
        description: "客戶報價作業",
        active: true,
      },
      {
        id: "sales",
        label: "銷貨單",
        icon: "ShoppingCart",
        href: "/sales",
        description: "銷貨出貨作業",
        active: true,
      },
      {
        id: "sales-return",
        label: "銷貨退回",
        icon: "RotateCcw",
        href: "/sales-returns",
        description: "客戶退貨作業",
        active: true,
      },
    ],
  },
  {
    id: "vendor",
    label: "廠商端",
    color: "green",
    items: [
      {
        id: "vendors",
        label: "廠商資料",
        icon: "Truck",
        href: "/vendors",
        description: "廠商基本資料管理",
        active: true,
      },
      {
        id: "purchase",
        label: "採購單",
        icon: "ClipboardList",
        href: "/purchase",
        description: "採購訂單作業",
        active: true,
      },
      {
        id: "receiving",
        label: "進貨單",
        icon: "PackageCheck",
        href: "/receiving",
        description: "廠商進貨管理",
        active: true,
      },
      {
        id: "purchase-return",
        label: "進貨退出",
        icon: "PackageX",
        href: "/purchase-returns",
        description: "進貨退出作業",
        active: true,
      },
    ],
  },
  {
    id: "inventory",
    label: "商品與財務端",
    color: "blue",
    items: [
      {
        id: "products",
        label: "商品資料",
        icon: "Package",
        href: "/products",
        description: "商品基本資料管理",
        active: true,
      },
      {
        id: "stock",
        label: "庫存管理",
        icon: "Warehouse",
        href: "/stock",
        description: "庫存查詢與調整",
        active: true,
      },
      {
        id: "reports",
        label: "進銷存報表",
        icon: "BarChart3",
        href: "/reports",
        description: "客戶銷售排名、暢銷商品分析",
        active: true,
      },
      {
        id: "finance",
        label: "財務報表",
        icon: "TrendingUp",
        href: "/finance",
        description: "應收帳款對帳單",
        active: true,
      },
      {
        id: "accounting",
        label: "快速記帳",
        icon: "Calculator",
        href: "/accounting",
        description: "支出收入快速記帳",
        active: true,
      },
      {
        id: "invoice-statistics",
        label: "發票統計明細",
        icon: "Receipt",
        href: "/invoice-statistics",
        description: "進出貨發票統計明細",
        active: true,
      },
      {
        id: "invoice-helper",
        label: "電子發票助手",
        icon: "FileCheck",
        href: "/invoice-helper",
        description: "電子發票查詢與管理",
        active: true,
      },
      {
        id: "audit-log",
        label: "操作日誌",
        icon: "History",
        href: "/audit-log",
        description: "系統操作記錄查詢",
        active: true,
      },
    ],
  },
];
